"""Contract tests for recast-recon.sh — comprehensive default, --traces-only, path:line only."""

import re

import pytest
from recast_helpers import RECON_SH, run

PATHLINE = re.compile(r"\S+:\d+")


def test_clean_tree(tmp_path):
    """A marker-free tree exits 0."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "a.txt").write_text("hello world\n")
    (tree / "b.txt").write_text("nothing to see here\n")

    res = run(RECON_SH, tree)
    assert res.returncode == 0, res.stderr


def test_ai_marker_present(tmp_path):
    """A trace marker hit exits 1, prints path:line, never the content."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "msg.txt").write_text("subject line\n\nCo-Authored-By: someone\n")

    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    assert PATHLINE.search(res.stdout), res.stdout
    assert "Co-Authored-By" not in res.stdout


def test_custom_pattern_matches(tmp_path):
    """A custom pattern from a positional file hits; content stays hidden."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "leak.txt").write_text("token is SECRET123 do not share\n")

    pattern_file = tmp_path / "patterns.txt"
    pattern_file.write_text("SECRET[0-9]+\n")

    res = run(RECON_SH, tree, pattern_file)
    assert res.returncode == 1, res.stderr
    assert PATHLINE.search(res.stdout), res.stdout
    assert "SECRET123" not in res.stdout


def test_comments_only_pattern_file(tmp_path):
    """A comments/blank-only pattern file must not trigger the empty grep -f footgun."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "a.txt").write_text("plain content\n")

    pattern_file = tmp_path / "patterns.txt"
    pattern_file.write_text("# just a comment\n\n   \n# another\n")

    res = run(RECON_SH, tree, pattern_file)
    assert res.returncode == 0, res.stderr
    assert res.stdout == ""


TRACE_FORMS = [
    "Co-Authored-By: someone\n",
    "co-authored by someone\n",  # space-form prose, not the hyphenated trailer
    "generated by a tool\n",
    "this is AI-assisted work\n",
    "\U0001f916 Generated with [Claude Code]\n",  # emoji + "generated with" footer
    "\U0001f916\n",  # pure emoji
]


@pytest.mark.parametrize("content", TRACE_FORMS)
def test_trace_forms_flagged_by_default(tmp_path, content):
    """Generation traces halt the gate; content stays hidden."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "f.txt").write_text(content)

    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    assert PATHLINE.search(res.stdout), res.stdout


NAME_FORMS = [
    "model = claude-opus-4-8\n",  # model id (substring 'claude')
    "see ~/.claude/projects/x/s.jsonl\n",  # session path
    "vendor: ANTHROPIC inc\n",  # uppercase Anthropic
    "protocol: GEMINI\n",
]


@pytest.mark.parametrize("content", NAME_FORMS)
def test_name_forms_flagged_by_default(tmp_path, content):
    """The comprehensive default scrubs tool-name mentions too; content stays hidden."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "f.txt").write_text(content)

    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    assert PATHLINE.search(res.stdout), res.stdout


@pytest.mark.parametrize("content", NAME_FORMS)
def test_traces_only_keeps_names(tmp_path, content):
    """--traces-only keeps tool-name mentions (they pass the gate)."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "f.txt").write_text(content)

    res = run(RECON_SH, "--traces-only", tree)
    assert res.returncode == 0, res.stderr


def test_traces_only_still_scrubs_traces(tmp_path):
    """--traces-only keeps names but still halts on generation traces."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "f.txt").write_text("Co-Authored-By: bot\n")

    res = run(RECON_SH, "--traces-only", tree)
    assert res.returncode == 1, res.stderr
    assert PATHLINE.search(res.stdout), res.stdout


def test_flag_shaped_positional_rejected(tmp_path):
    """A flag-shaped token in a positional slot fails loud (exit 2), never silently skips."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "a.txt").write_text("plain\n")

    res = run(RECON_SH, tree, "--redact")
    assert res.returncode == 2, res.stderr


def test_traces_only_trailing_flag_rejected(tmp_path):
    """--traces-only after the tree (wrong slot) fails loud (exit 2), not a silent skip."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "a.txt").write_text("plain\n")

    res = run(RECON_SH, tree, "--traces-only")
    assert res.returncode == 2, res.stderr


def test_missing_pattern_file_errors(tmp_path):
    """A pattern-file arg pointing at a missing path fails loud (exit 2)."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "a.txt").write_text("plain\n")

    res = run(RECON_SH, tree, tmp_path / "nope.txt")
    assert res.returncode == 2, res.stderr


def test_usage_lists_exit_codes():
    """usage() (no args) documents all three exit codes and the --traces-only flag."""
    res = run(RECON_SH)
    assert res.returncode == 2
    for tok in ("0", "1", "2", "--traces-only"):
        assert tok in res.stderr, res.stderr


def test_name_form_flagged_by_default(tmp_path):
    """A tool-name in a FILENAME (clean contents) halts the default gate."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "claude-config.md").write_text("plain content\n")
    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    # the path IS the tell; content stays hidden
    assert "claude-config.md" in res.stdout


def test_name_in_filename_kept_under_traces_only(tmp_path):
    """--keep-code keeps a legitimately Claude-named file."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "claude-config.md").write_text("plain content\n")
    assert run(RECON_SH, "--traces-only", tree).returncode == 0


def test_trace_marker_in_filename_flagged_both_modes(tmp_path):
    """A real TRACE marker in a filename halts in BOTH modes ('AI-assisted' is a marker)."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "AI-assisted-notes.txt").write_text("plain\n")
    for extra in ([], ["--traces-only"]):
        assert run(RECON_SH, *extra, tree).returncode == 1, extra


def test_utf16le_content_marker_caught(tmp_path):
    """A provenance marker in a UTF-16LE file must NOT slip the scrub open."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "notes.md").write_bytes(
        "Co-Authored-By: Claude <noreply@anthropic.com>\n".encode("utf-16-le")
    )
    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    assert ":wide" in res.stdout
    assert "Claude" not in res.stdout  # path-only, never content


def test_utf16be_content_marker_caught(tmp_path):
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "doc.md").write_bytes("generated with a tool\n".encode("utf-16-be"))
    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    assert ":wide" in res.stdout


def test_clean_utf16_stays_clean(tmp_path):
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "plain.md").write_bytes("just some plain notes\n".encode("utf-16-le"))
    res = run(RECON_SH, tree)
    assert res.returncode == 0, res.stderr


def test_binary_file_no_false_positive_or_error(tmp_path):
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "img.png").write_bytes(b"\x89PNG\x00\x00\x00\x00binarydata")
    res = run(RECON_SH, tree)
    assert res.returncode == 0, res.stderr
    assert res.stderr == "", res.stderr  # no NUL-byte warnings


def test_symlink_target_marker_caught(tmp_path):
    """A symlink whose TARGET path carries a marker is a tell — scan the target string."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "link").symlink_to("/home/x/.claude/hooks/foo.sh")
    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr
    assert ":symlink-target" in res.stdout


def test_no_hyphen_trace_variants_caught(tmp_path):
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "a.txt").write_text("this was generated using automation\n")
    (tree / "b.txt").write_text("AI assisted draft\n")
    res = run(RECON_SH, tree)
    assert res.returncode == 1, res.stderr


def test_custom_pattern_matches_filename(tmp_path):
    """A custom --redact pattern must sweep file/dir NAMES too, not only contents (a marker in a
    filename is just as much a tell)."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "copilot-notes.md").write_text("nothing sensitive in the body\n")
    pattern_file = tmp_path / "patterns.txt"
    pattern_file.write_text("[Cc]opilot\n")

    res = run(RECON_SH, tree, pattern_file)
    assert res.returncode == 1, res.stderr
    assert ":name" in res.stdout, res.stdout


def test_custom_pattern_matches_symlink_target(tmp_path):
    """A custom --redact pattern must sweep symlink TARGET strings too."""
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "link").symlink_to("../copilot/config.json")
    pattern_file = tmp_path / "patterns.txt"
    pattern_file.write_text("[Cc]opilot\n")

    res = run(RECON_SH, tree, pattern_file)
    assert res.returncode == 1, res.stderr
    assert ":symlink-target" in res.stdout, res.stdout
