#!/usr/bin/env bash
# shellcheck disable=SC2034  # TRACE_MARKERS/NAME_MARKERS are consumed by scripts that source this
set -euo pipefail

# Script: recast-markers.sh
# Purpose: Single source of truth for the recon marker arrays. SOURCED, not executed —
#          both recast-recon.sh and recast-recon-history.sh source it so the sets cannot drift.
# Usage: . "$(dirname "$0")/recast-markers.sh"

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  printf 'Cannot run directly. Usage: source %s\n' "$0" >&2
  exit 1
fi

# TRACE_MARKERS: genuine "a bot made this" metadata — case-insensitive fixed substrings.
TRACE_MARKERS=(
  -e 'Co-Authored-By'
  -e 'co-authored by'
  -e 'generated by'
  -e 'generated with'
  -e 'generated using'
  -e 'AI-assisted'
  -e 'AI assisted'
  -e '🤖'
)
# NAME_MARKERS: tool names matched as substrings, so 'Claude' also catches .claude, claude.ai,
# claude-code, model ids (claude-opus-4), .claude/ paths, and legitimate AI-topic text. Swept by
# default (comprehensive scrub — a recast should not reveal AI involvement); --traces-only drops
# them for textual surfaces so a source that legitimately discusses these tools keeps its mentions.
NAME_MARKERS=(
  -e 'Claude'
  -e 'Anthropic'
  -e 'GEMINI'
)
